# Generated by Django 3.2.18 on 2023-02-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_tag', models.CharField(default='UA-151236093-1', max_length=255)),
                ('event', models.CharField(default='event', max_length=255)),
                ('cn_tag', models.CharField(default='hrbrand', max_length=255)),
                ('cs_tag', models.CharField(default='corpemail', max_length=255)),
                ('ec_tag', models.CharField(default='email', max_length=255)),
                ('ea_tag', models.CharField(default='open', max_length=255)),
                ('el_tag', models.CharField(default='221003gvk', max_length=255)),
                ('field_name', models.FileField(upload_to='files/')),
            ],
        ),
    ]
